language:
  - python

python:
  - "3.7"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - export FLASK_APP="manage.py"
  - export ENVIRONMENT="testing"
  - psql -c 'create database lms_test;' -U postgres
  - export DATABASE_URL='postgresql://postgres@localhost:5432/lms_test'
  - flask db stamp heads
  - flask db migrate
  - flask db upgrade

script:
  - pytest --cov=app/

after_script:
  - coveralls
