version: "3.7"
services:
  database:
    restart: "no"
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lms_db
    ports:
      - '5432:5432'
  lms-api:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:5000"
