"""empty message

Revision ID: 512185d8a9a1
Revises: 568addbd3024
Create Date: 2019-10-24 14:38:54.652543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '512185d8a9a1'
down_revision = '568addbd3024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_admin',
    sa.Column('name', sa.String(length=75), nullable=True),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('person_user',
    sa.Column('name', sa.String(length=75), nullable=True),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_author', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('social_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('excerpt', sa.String(length=275), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_download_url', sa.String(), nullable=True),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=75), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['person_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('subject_lecture', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_lecture'], ['lecture.id'], ),
    sa.ForeignKeyConstraint(['user'], ['person_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('lecture')
    op.drop_table('person_user')
    op.drop_table('person_admin')
    # ### end Alembic commands ###
