"""empty message

Revision ID: 568addbd3024
Revises: 89cee6f112ce
Create Date: 2019-10-24 14:37:17.729853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '568addbd3024'
down_revision = '89cee6f112ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_user',
    sa.Column('name', sa.String(length=75), nullable=True),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_author', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('social_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_foreign_key(None, 'lecture', 'person_user', ['author'], ['id'])
    op.create_foreign_key(None, 'review', 'person_user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'lecture', type_='foreignkey')
    op.drop_table('person_user')
    # ### end Alembic commands ###
