"""empty message

Revision ID: 89cee6f112ce
Revises: 417fdc57b378
Create Date: 2019-10-23 12:03:08.656040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cee6f112ce'
down_revision = '417fdc57b378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person_admin', 'name',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
    op.alter_column('person_user', 'name',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person_user', 'name',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
    op.alter_column('person_admin', 'name',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
    # ### end Alembic commands ###
