"""empty message

Revision ID: cff6109dd4ce
Revises: aa5d88facf6a
Create Date: 2019-10-24 19:01:48.922900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff6109dd4ce'
down_revision = 'aa5d88facf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture', sa.Column('transcript', sa.Text(), nullable=True))
    op.alter_column('lecture', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lecture', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('lecture', 'transcript')
    # ### end Alembic commands ###
